### ISSUE TITLE
Flake with nix-darwin failing to build on aarch64-darwin

### ISSUE THREAD

**Issue by jmgilman** [DeterminateSystems/fh#180]
## Error
```
Error: 
   0: failed to copy resolved store path with Nix
   1: Failed to copy resolved store path with Nix
   2: Nix command `"nix" "--extra-experimental-features" "nix-command flakes" "copy" "--option" "narinfo-cache-negative-ttl" "0" "--from" "https://cache.flakehub.com/" "/nix/store/22z349qnh61qqx9s848w9ih3nsyymhd5-darwin-system-25.05.4515dac" "--netrc-file" "/var/folders/gv/kllfch6d5l9dq4676hq4260m0000gn/T/.tmpgFgq2l/netrc"` failed; check prior Nix output for details
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.22|
|**os**|macos|
|**arch**|aarch64|

The source flake is private, but I can share the base `flake.nix` here:

```
{
  description = "Darwin configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    darwin.url = "github:lnl7/nix-darwin";
    darwin.inputs.nixpkgs.follows = "nixpkgs";
    fh.url = "https://flakehub.com/f/DeterminateSystems/fh/*";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = inputs@{ nixpkgs, home-manager, darwin, ... }: {
    darwinConfigurations = {
      "jmgilman-mbp" = darwin.lib.darwinSystem {
        system = "aarch64-darwin";
        specialArgs = { inherit inputs; };
        modules = [
          ./configuration.nix
          home-manager.darwinModules.home-manager
          {
            home-manager.users.josh = import ./home;
          }
        ];
      };
    };
  };
}
```

Builds fine with:

```
nix run nix-darwin -- switch --flake /path/to/flake
```

**Comment by jmgilman** [comment]
Yes, if you look at the first line of the error output, you can see the command I am running (which references a flake on FlakeHub). However, as I mentioned, the flake is private.

**Comment by cole-h** [comment]
Could you also post your CI workflow file? This _should_ work just fine if you have the `flakehub-cache-action` running and build that flake attr in any job with `flakehub-cache-action`...

**Comment by jmgilman** [comment]
```
name: Publish every Git push to main to FlakeHub
on:
  push:
    branches:
      - master

jobs:
  flakehub-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          rolling: true
          visibility: private
          include-output-paths: true
```

I just copied and pasted the one from the getting started guide. I assumed it was working because it passed and the flake showed up on FlakeHub. The FlakeHub UI also reports there's an `darwinConfigurations.jmgilman-mbp` output in the flake. So I think it's working.
